### ISSUE TITLE
Zweideutigkeit recordConstructDecl und Funktionaufruf

### ISSUE THREAD

**Issue by paulsonnenschein** [Linschlager/iml-compiler#5]
Ich habe das ganze noch nicht in fix und foxi getestet, aber ich glaube wir haben eine zweideutigkeit in userer grammatik.

Mir ist aufgefallen das wir mit dem aktuellen Vorschlag keine verschachtelten records erstellen können (<recordConstructDecl> ist nur als command, aber nicht als expression erlaubt).

Aber bei den expressions gibt es auch folgende regel: `<factor> ::= <ident> [init | <exprList>]` die ja genau (abgesehen von init) `<recordConstructDecl> ::= <ident> <exprList>` entspricht.

Nun können wir entweder sagen das wir einfach die beiden sachen "mergen" und später anhand vom identifier unterscheiden ob es eine funktion oder ein record ist (record-/funktionsname muss dann unique sein), oder wir passen die grammatik so an das es eindeutig ist um was es geht (immer einen record prefix vorne dran??).

Die erste vriant könnte man so sehen das für einen record immer eine art constructor funktion generiert wird...

Was meinst du @Linschlager ?

**Comment by Linschlager** [comment]
Ich mag den ersten Ansatz. Das sieht meiner Meinung nach schlussendlich im Code sonst komisch aus.
`p1 init := record vector2d(record point2d(0, 0), record point2d(0,0))` vs `p1 init := vector2d(point2d(0, 0), point2d(0,0))` macht schon was aus bezüglich Lesbarkeit

**Comment by Linschlager** [comment]
Aber ich denke, wenn wir das noch in Fix&Foxi anschauen, sollten wir auch ausprobieren können, ob das so überhaupt möglich ist und sonst eine Alternative ausprobieren, die es ist.
